-- MySQL Script generated by MySQL Workbench
-- Thu Jul  1 06:55:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dentista` DEFAULT CHARACTER SET utf8 ;
USE `dentista` ;

-- -----------------------------------------------------
-- Table `dentista`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentista`.`Consultas` (
  `idConsultas` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Cpf` VARCHAR(12) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Profissional` VARCHAR(45) NOT NULL,
  `Data_con` DATETIME NOT NULL,
  `Valor` DECIMAL(6,2) NOT NULL,
  `Telefone` BIGINT NOT NULL,
  PRIMARY KEY (`idConsultas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from Consultas;
#drop database dentista;
